# Generated by Django 4.2.5 on 2023-10-25 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_compra_usuario_delete_project_compra_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='name',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='index.usuario'),
        ),
    ]
